[package]
name = "tokio-cron-scheduler"
version = "0.6.0"
authors = ["Michael van Niekerk <mike@agri-io.co.za>"]
edition = "2018"

documentation = "https://docs.rs/tokio_cron_scheduler/"
repository = "https://github.com/mvniekerk/tokio-cron-scheduler"

description = "Schedule tasks on tokio using cron-like annotation. Also schedule tasks at an instant or repeat them at a fixed duration."

license = "MIT/Apache-2.0"

readme = "README.md"
keywords = ["cron", "crontab", "scheduler", "job", "tokio"]

categories = ["date-and-time"]

[dependencies]
tokio = { version = "1", features = ["time", "rt"] }
cron = "0.8"
chrono = "0.4"
time = "0.1.44"
uuid = { version = "0.8", features = ["v4"] }
prost = "0.9"

[dependencies.nats]
git = "ssh://git@github.com/nats-io/nats.rs.git"
rev = "9e556c059f29752165eaa029885fb8836ca34dcf"
#branch = "main"
features = ["unstable"]
optional = true

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

[build-dependencies]
prost-build = { version = "0.9" }

[features]
signal = ["tokio/signal"]
nats_scheduler = ["nats"]
default = ["nats_scheduler"]


